### ISSUE TITLE
Mac OS X error

### ISSUE THREAD

**Issue by Schrank** [EcomDev/MageCI#1]
I have no idea what to do. If I understand it correct, readlink is not useable under OS X. Then it falls back to realpath, which is obviously missing :-/ Any ideas?

```
brank:tmp myUserName$ vendor/bin/mage-ci install /Users/myUserName/__htdocs/magento 1.7.0.2 mage -u mage -p naaYStF8wrNG3J45
readlink: illegal option -- f
usage: readlink [-n] [file ...]
vendor/bin/mage-ci: line 19: realpath: command not found
```

**Comment by IvanChepurnyi** [comment]
Seems like you don't have gnu tools.

**Comment by IvanChepurnyi** [comment]
There is only one workaround if you don't have realpath and readlink installed on the system:
http://stackoverflow.com/questions/1055671/how-can-i-get-the-behavior-of-gnus-readlink-f-on-a-mac

**Comment by Schrank** [comment]
I'll have a look on gnu tools, hopefully I can install realpath with home brew if not, I'll change mage-ci, thanks Ivan!

**Comment by Schrank** [comment]
I installed realpath: https://github.com/harto/realpath-osx and now it seems to work :)
